name: Dump firmware (full)

on:
  workflow_dispatch:
    inputs:
      ota:
        description: 'OTA'
        required: true
      release_version:
        description: 'Release version'
        required: true

jobs:
  dump:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup
      run: |
        sudo apt update
        sudo apt -y install aria2 zstd
        curl -L https://github.com/ssut/payload-dumper-go/releases/download/1.2.2/payload-dumper-go_1.2.2_linux_amd64.tar.gz -o - | tar zxf - payload-dumper-go

    - name: Download
      id: download
      run: |
        aria2c -q -s16 -x16 ${{ inputs.ota }} -o ota.zip

    - name: Dump
      run: |
        ./payload-dumper-go -o ota ota.zip > /dev/null
        pushd ota; for f in *; do zstd $f; done; popd

    - name: Upload release assets
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        body: ${{ inputs.ota }}
        tag_name: ${{ inputs.release_version }}
        files: ota/*.img.zst
